version: '3'

services:
  oncall:
    build: .
    restart: unless-stopped
    ports:
      - 8002:8080
    deploy:
      resources:
        reservations:
          devices:
          -  driver: nvidia
             count: all
             capabilities: [gpu]